### ISSUE TITLE
Code for model pre-training with SupCon 

### ISSUE THREAD

**Issue by JimZAI** [deeplearning-wisc/knn-ood#11]
Hi, 

Could you provide the code for model pre-training with SupCon.

Thanks.

**Comment by sunyiyou** [comment]
Sure, please see https://github.com/HobbitLong/SupContrast.

**Comment by JimZAI** [comment]
More concretely, 
could you provide the code or training scripts for the SupCon pretrained (ResNet-18) models adopted in Table 1.

**Comment by sunyiyou** [comment]
Plz use the repo above by changing the arch to resnet18 which takes one or two lines of editing in code.
