### ISSUE TITLE
Two questions about this paper

### ISSUE THREAD

**Issue by wjczf123** [deeplearning-wisc/knn-ood#12]
Hi, yiyou.
Thanks for your code and work. I have two questions about this paper:

1. I try the performance with varying k. The performance is as follows:

OOD detection method: KNN k=20
              FPR    AUROC  AUIN  
SVHN           2.31  99.54  99.54
LSUN           2.01  99.40  99.47
iSUN          20.10  96.71  97.62
dtd            8.09  98.55  99.19
places365     22.98  95.53  95.53
AVG           11.10  97.94  98.27

 OOD detection method: KNN k=50
              FPR    AUROC  AUIN  
SVHN           2.42  99.52  99.53
LSUN           1.78  99.48  99.53
iSUN          20.06  96.74  97.63
dtd            8.09  98.56  99.20
places365     22.91  95.51  95.47
AVG           11.05  97.96  98.27

 OOD detection method: KNN k=100
              FPR    AUROC  AUIN  
SVHN           2.52  99.51  99.51
LSUN           1.72  99.52  99.56
iSUN          19.98  96.74  97.62
dtd            8.03  98.57  99.20
places365     22.93  95.48  95.41
AVG           11.04  97.96  98.26

How to choose k according to the upper performance? Do I use AUIN to choose model? Which can be used as the result of the validation set?

2. Can you share the checkpoint of DenseNet after training of contrastive learning in Table 7?

**Comment by sunyiyou** [comment]
1. You can use a validation OOD dataset like Gaussian Noise image to select the model with the best AUROC. 

2. Please see https://github.com/deeplearning-wisc/knn-ood/issues/3.

**Comment by wjczf123** [comment]
Thanks! Best regards!
