### ISSUE TITLE
What is the minimum recommended sample size?

### ISSUE THREAD

**Issue by arjunsinghrathore** [deeplearning-wisc/knn-ood#13]
Hey! I wanted to ask what should Ideally be the minimum recommended sample size?

For example, I'm currently using 45000 samples for a train set, 10000 samples for the test set, and 50 samples for the OOD set. But not getting the expected results and think that maybe it might be related to the sample size of OOD set being too low?

So I wanted to ask what should be the minimum recommended sample size for the ood set and overall for other sets as well?

**Comment by sunyiyou** [comment]
Hi, 50 are too small for OOD testing. We usually have 10000 OOD samples for each OOD test set.
