### ISSUE TITLE
Can this method co-work with ReAct?

### ISSUE THREAD

**Issue by BierOne** [deeplearning-wisc/knn-ood#14]
Hi,

I sincerely appreciate your outstanding work! I am wondering if this method can be combined with your ReAct (NeurIPS'21). Could you comment on this? Thank you so much.

**Comment by sunyiyou** [comment]
Yes, we do have a small experiment in Table 6. But why the performance gets better is still a mystery.

**Comment by BierOne** [comment]
That's great! Would you mind releasing the detailed scores (FPR and AUCROC) on each dataset? This would be helpful if we want to explore this behavior. Thanks!
