### ISSUE TITLE
a question about a single data test

### ISSUE THREAD

**Issue by Afleve** [deeplearning-wisc/knn-ood#15]
I found  test data from ID is used to get threshold. data is regarded as ID or OD by this threshold.But when I have a single data, how to get this threshold.In the other word,how to determine whether a single data is OOD.

**Comment by sunyiyou** [comment]
FPR95 is a measurement of the test data, so the value of the 95th percentile is directly picked based on the test ID. 
In an actual pipeline, the threshold can be picked by training ID data, which allows you to separate a single data point.
