### ISSUE TITLE
Some questions about the score_log variable under run_cifar.py

### ISSUE THREAD

**Issue by 0nem0relight** [deeplearning-wisc/knn-ood#16]
python run_cifar.py --in-dataset CIFAR-10  --out-datasets SVHN LSUN iSUN dtd places365 --name resnet18-supcon  --model-arch resnet18-supcon
When I executed the above command and applied np.argmax(score_log,axis=1), I found that the prediction result was wrong, only 1202 data were predicted correctly。
<img width="274" alt="image" src="https://github.com/deeplearning-wisc/knn-ood/assets/140148974/960216ed-8e67-47cb-8344-91eee243b82b">

<img width="907" alt="image" src="https://github.com/deeplearning-wisc/knn-ood/assets/140148974/8f654371-113d-46b8-929c-79eeddd4360c">
Is there something wrong here？

**Comment by sunyiyou** [comment]
Hi there, we only need the feature in the penultimate layer for KNN-based OOD detection.
