### ISSUE TITLE
about a bug when I run run_cifar.py file

### ISSUE THREAD

**Issue by ZZK-888** [deeplearning-wisc/knn-ood#21]
there is my mistake ,could you reply me? thank you very much!
![ood](https://github.com/deeplearning-wisc/knn-ood/assets/104481573/3b5620d3-e63e-4fb5-a0c2-e7bd7d501b5a)

**Comment by sunyiyou** [comment]
Hi there, you will need to follow the instruction in readme.md to run the code.
