### ISSUE TITLE
pre-trained model has become invalid

### ISSUE THREAD

**Issue by drafttim** [deeplearning-wisc/knn-ood#22]
The Google email address storing the pre-trained model has become invalid. We hope it can be re-uploaded.
![image](https://github.com/deeplearning-wisc/knn-ood/assets/128781339/d5f2956c-f4fa-4b1d-84f2-32308813e0b2)

**Comment by sunyiyou** [comment]
Thanks for the reminder! Here is the updated link: 
https://drive.google.com/file/d/13qZeK05YgVWRAHHdl_s20Yb8gKZgP0dG/view?usp=drive_link
