### ISSUE TITLE
Checkpoints/Model DenseNet-101 from Table 7

### ISSUE THREAD

**Issue by aqibsaeed** [deeplearning-wisc/knn-ood#3]
Hi,

Could you please share the model and checkpoints for CIFAR-10  and 100 that has been used in Table 7?
 Thanks.

**Comment by sunyiyou** [comment]
Sure, plz see. 
https://drive.google.com/drive/folders/1JQqKs0GKz6tkJUpp1BBBHZgCk4R151aj?usp=sharing

**Comment by aqibsaeed** [comment]
Thanks. Could you share the fix for this line too please? I believe, this is not aligned with dense-net architecture.

https://github.com/deeplearning-wisc/knn-ood/blob/1e4aabc68b026afa5bed7ffa5258bc37df3a91cd/run_cifar.py#L36

**Comment by sunyiyou** [comment]
Hi, the current code repo is for ResNet only. 

If you are interested in DenseNet, you can manually change the array slicing to the **last** 342 dimensions, as we only use the penultimate layer's features.

**Comment by aqibsaeed** [comment]
Thanks.  Is this correct then?
` prepos_feat = lambda x: np.ascontiguousarray(normalizer(x[:, range(282, 624)]))# Last Layer only `

**Comment by aqibsaeed** [comment]
@sunyiyou

**Comment by sunyiyou** [comment]
I would suggest you could try it out with what you have here.
