### ISSUE TITLE
ImageNet model without contrastive loss

### ISSUE THREAD

**Issue by litianliu** [deeplearning-wisc/knn-ood#5]
Hi,
Can you please share the checkpoint of ImageNet model trained without contrastive learning in Table 4? 
Thanks!

**Comment by sunyiyou** [comment]
Sure, we use the default model provided by Pytorch. 
https://github.com/deeplearning-wisc/knn-ood/blob/1e4aabc68b026afa5bed7ffa5258bc37df3a91cd/util/model_loader.py#L15
