### ISSUE TITLE
Checkpoints of the classifiers on top of supçon models

### ISSUE THREAD

**Issue by litianliu** [deeplearning-wisc/knn-ood#6]
Hi, 

Can you please share the checkpoints of the classifiers corresponding to the ID ACC with contrastive loss in table 1, table 4, and table 7? The shared supcon models seem to only contain the contrastive heads but not the final classifier on top of the learnt representation. 

Thanks a lot!

**Comment by sunyiyou** [comment]
Yes, the original training pipeline does not contain a linear head. I reported the accuracy by 
https://github.com/HobbitLong/SupContrast/blob/master/main_linear.py

Since the feature backbone is fixed, the trained come be done in several minutes (CIFAR) or several hours (ImageNet).

**Comment by litianliu** [comment]
Thank you for your reply! With the provided checkpoint and the supcon repo training script, I can only achieve an ID acc of 94.64% instead of 95.07% for Cifar10 in your paper. Can you please let me know if you have changed any of the default parameters? Thanks!

**Comment by sunyiyou** [comment]
A gap with 0.4% can very easily fall in to the variance of a random seed. If your goal is a higher ACC, I suggest following the full pipeline in https://github.com/HobbitLong/SupContrast.  The reported ACC is around 96%.

**Comment by litianliu** [comment]
got it. thank you!

**Comment by matchyc** [comment]
> Yes, the original training pipeline does not contain a linear head. I reported the accuracy by https://github.com/HobbitLong/SupContrast/blob/master/main_linear.py
> 
> Since the feature backbone is fixed, the trained come be done in several minutes (CIFAR) or several hours (ImageNet).

Hi, @sunyiyou I noticed that you said "the feature back bone is fixed", do you mean that I can only train the linear head for classification? I don't see the training script providing such a function. How can I combine the checkpoint with the linear head?

Thank you in advance.

**Comment by matchyc** [comment]
Also trying to evaluate acc, thanks to this issue.

**Comment by matchyc** [comment]
> Thank you for your reply! With the provided checkpoint and the supcon repo training script, I can only achieve an ID acc of 94.64% instead of 95.07% for Cifar10 in your paper. Can you please let me know if you have changed any of the default parameters? Thanks!

aligning with this acc
