### ISSUE TITLE
Cannot reproduce the ImageNet results

### ISSUE THREAD

**Issue by yfzhang114** [deeplearning-wisc/knn-ood#8]
I run the default code for imagenet with contrastive loss, however, I get some strange results

nohup: ignoring input
  warnings.warn(f"A NumPy version >={np_minversion} and <{np_maxversion}"
Namespace(argument=True, base_dir='output/ood_scores', batch_size=64, cal_metric=False, depth=40, droprate=0.0, epochs=100, gpu='0', growth=12, imagenet_root='./datasets/imagenet/', in_dataset='imagenet', in_dist_only=False, layers=100, lr=0.1, method='', model_arch='resnet50-supcon', momentum=0.9, name='resnet50-supcon', out_datasets=['inat', 'sun50', 'places50', 'dtd'], out_dist_only=False, p=0, reduce=0.5, save_epoch=10, scale_ood=10.0, seed=0, start_epoch=0, t_margin_id=2.0, t_margin_ood=1.0, weight_decay=0.0001, width=4)
0
 OOD detection method: KNN
              FPR    AUROC  AUIN  
inat         100.00   0.13  42.00
sun50        100.00   0.12  41.95
places50     100.00   0.12  41.94
dtd          100.00   0.13  45.49
AVG          100.00   0.12  42.85

**Comment by sunyiyou** [comment]
You may want to check if the feature is correctly extracted.
