### ISSUE TITLE
Choice of layers

### ISSUE THREAD

**Issue by futakw** [deeplearning-wisc/knn-ood#9]
Hi, I have a question about layer choice.

In this repo, features for early layers are also extracted. But only the penultimate layer is used in the paper.
If you've tried, could you mention the usefulness of early layers?

Best,

**Comment by sunyiyou** [comment]
Hi, 

You can try to use multiple layers, which can be regarded as an extension of this method. Empirically, I tried directly concatenating features in all layers. The performance is not stable across evaluation settings. 

It also raises new problems: 
1. Is the features in all layers equally important?
2. How do you combine the layers in an optimal way? 

The investigation of these problems is important for future research, though beyond the scope of this paper.

**Comment by futakw** [comment]
Thank you so much for your quick response!
